# Generated by Django 4.2.18 on 2025-03-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_image_blob_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='message_images/'),
        ),
    ]
